### ISSUE TITLE
Unable to register with MQTT Broker

### ISSUE THREAD

**Issue by chris-burrow-apps** [jeroenboumans/PimoroniGrowKit-MQTT#1]
Upon cloning/configuring/installing the repo. The MQTT Broker is not reciving any topics set my the config.

From MQTT Broker:
1635457941: New connection from 192.168.50.20 on port 1883.
1635457941: New client connected from 192.168.50.20 as auto-432EAB4D-C27D-6B5A-0F3A-FA426B782128 (p2, c1, k60, u'mqtt_broker').
1635457951: Socket error on client auto-432EAB4D-C27D-6B5A-0F3A-FA426B782128, disconnecting.

**Comment by chris-burrow-apps** [comment]
I seem to get intemitant connection to MQTT Broker. Manually booting ./watcher.py logs below but listening for the topic shows it never gets recieved. Other devices recieve correctly.

Start submitting sensor data on MQTT topic /home/bedroom/plants
{"light": 0, "sensor_0": {"moisture": 0, "saturation": 1.0}, "sensor_1": {"moisture": 0, "saturation": 1.0}, "sensor_2": {"moisture": 0, "saturation": 1.0}}
{"light": 3.48555, "sensor_0": {"moisture": 4.8310855171466915, "saturation": 0.846}, "sensor_1": {"moisture": 4.831475066603634, "saturation": 0.846}, "sensor_2": {"moisture": 14.691559165609812, "saturation": 0.48}}

**Comment by chris-burrow-apps** [comment]
I have found adding a time.sleep(90) above the setup of the server made it very reliable. May be a system startup ordering issue.

**Comment by jeroenboumans** [comment]
The package uses the `paho.mqtt.client` package. Did you try debugging your connection using [MQTT Explorer](https://github.com/thomasnordquist/MQTT-Explorer)? Most issues originate from a wrong broker config or credentials. It also should register the script as a service. Do you see it running? It might take a couple of seconds before submitting after reboot.

**Comment by chris-burrow-apps** [comment]
I managed to get it working. Seems like I needed to add a delay to start of script as when my Home Assistant reboot, this could not connect as the server was not initialised.
